using System;
using System.Linq;
using System.Runtime.InteropServices;
using Server.Items;
using System.Collections.Generic;

namespace Server.Misc
{
 		
        class GodInit 
        {
				public static void Configure()
					{
							God.RegisterGod(new God(-1, "Aucun", new Dictionary<MagieType, int>(), 302,40, "H??#$?&*r??#$?&*tique !"));

							God.RegisterGod(new God(0, "Greald", new Dictionary<MagieType, int>() { { MagieType.Obeissance, 8}, }, 303,0, "Animal Repr??#$?&*sentatif: Loup \n\nArme repr??#$?&*sentative: ??#$?&*p??#$?&*e \n\nLogo Repr??#$?&*sentatif: Une balance \n\nD??#$?&*votion: Ob??#$?&*issance \n\nCroyance: Protection, Courage, Justice, Naissance, Beaut??#$?&*, Sacrifice, Endurance \n\nAntagoniste: Seras \n\nLes D??#$?&*vou??#$?&*s: \n\nLes loyalistes, les traditionnalistes et les respectueux du prestige sont souvent relier à Greald. Les Magistrats, Les politiciens, les militaires ont tendances à pencher vers l’??#$?&*thique que Greald leur apportes. Après tout pourquoi se plier à une d??#$?&*ch??#$?&*ance de l’ordre qui fera vivre un enfer sur terre dans le manque de respect ? \n\nHistoire: \n\nOn ne sait que très peu de choses sur Greald dit le loyaliste mise à part qu’il d??#$?&*clara alors une chasse de sang sur la tête de Seras pour avoir os??#$?&* corrompre les esprits des gens droit et disciplin??#$?&*. La l??#$?&*gende raconte que le loup aurait ??#$?&*t??#$?&* pi??#$?&*ger par le serpent lors d’un ??#$?&*change sur le mont Gruydia. \n\nLe coup d’??#$?&*p??#$?&*e lancer par Greald fut si violent que la montagne s’??#$?&*crasa sous la puissance de l’??#$?&*p??#$?&*e, alors que les gens pensaient se sortir de la guerre, Greald ramena alors ses troupes vers le chemin et leur montra alors la voie à prendre. Un seul commandement aurait ??#$?&*t??#$?&* ??#$?&*nonc??#$?&* par le fauve \n\n‘’Suivez les ordres!’’  "));
							God.RegisterGod(new God(1, "Quirel", new Dictionary<MagieType, int>() { { MagieType.Vie, 8 }, }, 304,8, "Animal Repr??#$?&*sentatif : Oiseau \n\nArme Repr??#$?&*sentative: Arc à flèche \n\nLogo Repr??#$?&*sentatif: Une lune dans un soleil \n\nD??#$?&*votion: Vie \n\nCroyance: Paix, L’Amour, Lune et Soleil, Divination et Destin, Sant??#$?&*, Prosp??#$?&*rit??#$?&*, Bienveillance \n\nAntagoniste: Zox \n\nLes D??#$?&*vou??#$?&*s: \n\nLes bons vivants, Honorable, Protecteur est souvent relier à Quirel. Chevalier, Paladin, Prêtre ont tendance à pencher vers la morale que Quirel leur procure. Après tout pourquoi essayer de faire le mal qui est tellement facile alors que nous pourrions juste aider et pardonner son prochain ? \n\nHistoire: \n\n On ne sait que très peu de chose sur Quirel dit le bienveillant mise à part qu’il d??#$?&*cida d’avouer son amour pour Zox et que le tout fini dans une rage pour le chien de la mort. Alors que Quirel tenta alors de ramener Zox qui ??#$?&*tait hors de lui. Le chien d??#$?&*cida de planter une flèche dans son propre cœur avant de disparaître dans le n??#$?&*ant. Quirel ayant perdu son ami mais aussi l’amour de sa vie d??#$?&*cida de s’??#$?&*lever dans le ciel pour prosp??#$?&*rer sur le royaume. Si lui ne pouvait connaitre l’amour alors il s’efforcerait que d’autre le d??#$?&*couvre."));
							God.RegisterGod(new God(2, "Seras", new Dictionary<MagieType, int>() { { MagieType.Anarchique, 8 }, }, 305,5, "Animal Repr??#$?&*sentatif: Serpent \n\n Arme Repr??#$?&*sentative: Dague \n\nLogo Repr??#$?&*sentatif: ??#$?&*toile à huit branches - L’octogramme \n\nD??#$?&*votion: Anarchique \n\nCroyance: Chance, Mensonge, Libert??#$?&*, M??#$?&*t??#$?&*o, Luxure, Chasse, Richesse \n\nAntagoniste: Greald \n\nLes D??#$?&*vou??#$?&*s: \n\nLes anarchistes, les esprits libertins et les Individualistes sont souvent relier à Seras. Pirates, Barbares, Bardes, Sorcier ont tendances à pencher vers l’??#$?&*thique que Seras leur apportes. Après tout pourquoi se plier à des lois ??#$?&*crites qui n’ont aucun sens et qui nous affaiblit ? \n\nHistoire \n\nOn ne sait que très peu de chose sur Seras dit l’anarchiste mise à part qu’il d??#$?&*cida de confronter le prestige de Greald. Remettant en doute l’encadrement et le dogme strict qu’apportait le loyaliste loup. Alors que tout ??#$?&*tait si limpide et carr??#$?&*, Seras d??#$?&*cida de mettre une touche de chaos dans cet ordre absolu, laissant au passage des mortels s’??#$?&*lever et prôner avec ferveur que s’en ??#$?&*tait assez de cette ob??#$?&*issance. Seras aurait donc initier les sens de rebellions et de libertinage. Jusqu’à quel prix ? Où ??#$?&*tait prêt à aller les mortels pour d??#$?&*fier les divinit??#$?&*s ? "));
							God.RegisterGod(new God(3, "Zox", new Dictionary<MagieType, int>() { { MagieType.Mort, 8 }, }, 306,0, "Animal Repr??#$?&*sentatif: Chien \n\nArme Repr??#$?&*sentative: Hache \n\nLogo Repr??#$?&*sentatif: Une croix relief d’un cercle au bout(Une Ankh) \n\nD??#$?&*votion: Mort \n\nCroyance: Gourmandise, Mort, Souffrance, Maladie, Colère, L’Orgueil, Rancune \n\nAntagoniste: Quirel\n\nLes D??#$?&*vou??#$?&*s : \n\nCalculateur, Manipulateur et Insensible est souvent relier à Zox. Roublard, Criminel, Meurtrier ont tendance à pencher vers la morale que Zox leur procure. Pourquoi essayer de faire le bien alors que sa n’apporte rien sauf un ‘’Merci’’ ? Aussi bien s??#$?&*vir et abuser des gens. \n\nHistoire \n\nOn ne sait que très peu de chose sur Zox outre le fait qu’il a d??#$?&*cider de renier l’amour de Quirel. La l??#$?&*gende raconte qu’en fait Zox ??#$?&*tait très malade, il ??#$?&*tait sur le seuil de mourir d’une maladie d??#$?&*g??#$?&*n??#$?&*rative, il pensait que les sages conseils de Quirel pourraient le gu??#$?&*rir mais au lieu de cela l’oiseau lui dicta un amour ce qui ne plus au chien de la mort. Zox d??#$?&*cida ainsi de disparaître dans les profonds abysses du monde, reniant et maudissant la vue du soleil et de la lune. Pour lui l’oiseau l’avait trahi, au lieu de le sauver il lui proposa que de l’amour ? En quoi l’amour pourrait - il me sauver se disait le canin."));
							God.RegisterGod(new God(4, "Celus", new Dictionary<MagieType, int>() { { MagieType.Cycle, 8 }, }, 307,13, "Animal Repr??#$?&*sentatif: Crocodile ou Dragon \n\nArme Repr??#$?&*sentative: Mace \n\nLogo Repr??#$?&*sentatif: Un huit sur le côt??#$?&*(Symbole de l’infini) \n\nD??#$?&*votion: Cycle \n\nCroyance: Agriculture, Renaissance, Artiste, Nature, Guerre, Magie, Connaissance \n\nAntagoniste: Aucun \n\nLes D??#$?&*vou??#$?&*s: Les ??#$?&*nigmatiques, M??#$?&*diateurs et Impartial sont souvent relier à Celus. Philosophe, Magicien et Artiste ont tendance à pencher vers l’??#$?&*thique et moral que Celus leur procure. Après tout pourquoi peser le pour et le contre de tout ses choix ? Restons neutre et profitons du cycle ??#$?&*ternel. \n\nHistoire: \n\nOn ne sait que très peu de chose sur Celus dit l’??#$?&*ternel mise à part qu’il d??#$?&*cida de rester en dehors de la guerre des divinit??#$?&*s. Alors que tous voulaient avoir l’appuis du cycle, Celus d??#$?&*cida de rester en plein milieu de la mer pendant sept jours à contempler ainsi le d??#$?&*sastre de la guerre. Il attendait patiemment et continuait de regarder juste le vide. La l??#$?&*gende raconte que Celus s’aurait endormit au fond de la mer face à tous ses choix. Quel ennuie se disait - il où attendait - il d’effectuer son travail ad??#$?&*quatement ? "));

		
					}
		}
}
